FROM golang:latest

MAINTAINER Seungkyu Ahn (seungkyua@gmail.com)

RUN mkdir /app
ADD config /app/config
WORKDIR /app

COPY bin/cookiemonster* /app/cookiemonster

EXPOSE 8080

CMD ["/app/cookiemonster"]