// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/rbxo/v1alpha1.Cookiemonster":       schema_pkg_apis_rbxo_v1alpha1_Cookiemonster(ref),
		"./pkg/apis/rbxo/v1alpha1.CookiemonsterSpec":   schema_pkg_apis_rbxo_v1alpha1_CookiemonsterSpec(ref),
		"./pkg/apis/rbxo/v1alpha1.CookiemonsterStatus": schema_pkg_apis_rbxo_v1alpha1_CookiemonsterStatus(ref),
	}
}

func schema_pkg_apis_rbxo_v1alpha1_Cookiemonster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Cookiemonster is the Schema for the cookiemonsters API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/rbxo/v1alpha1.CookiemonsterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/rbxo/v1alpha1.CookiemonsterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/rbxo/v1alpha1.CookiemonsterSpec", "./pkg/apis/rbxo/v1alpha1.CookiemonsterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_rbxo_v1alpha1_CookiemonsterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CookiemonsterSpec defines the desired state of Cookiemonster",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_rbxo_v1alpha1_CookiemonsterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CookiemonsterStatus defines the observed state of Cookiemonster",
				Type:        []string{"object"},
			},
		},
	}
}
