---
apiVersion: v1
kind: Service
metadata:
  name: cookiemonster
  namespace: cookiemonster
  labels:
    component: cookiemonster
spec:
  selector:
    app: cookiemonster
  ports:
    - name: http
      protocol: TCP
      nodePort: 30003
      port: 8080
      targetPort: 8080
  type: NodePort
