apiVersion: rbxo.coockie.com/v1alpha1
kind: Cookiemonster
metadata:
  name: cookiemonster-example
spec:
  data:
    size: 1
    namespace:
      - name: openstack
        resource:
          - kind: deployment
            name:
            target: 1
          - kind: daemonset
            name:
            target: 1
          - kind: statefulset
            name: mariadb
            target: 1
          - kind: statefulset
            name: rabbitmq
            target: 1
    interval: 60
    duration: 600
    slack: true
    change: true
    bmcad: 192.168.0.0
